// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLVY7XExwxwyfOT-GuhFiho6mdpHck8hc',
    appId: '1:82853880537:web:0ba738f40bf1e03d75d4c8',
    messagingSenderId: '82853880537',
    projectId: 'calendar-management-233888',
    authDomain: 'calendar-management-233888.firebaseapp.com',
    storageBucket: 'calendar-management-233888.appspot.com',
    measurementId: 'G-TPX93MXW7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC336ho8MZR6--_nP4BEGV89aN5DXh88rU',
    appId: '1:82853880537:android:545a9751873332e175d4c8',
    messagingSenderId: '82853880537',
    projectId: 'calendar-management-233888',
    storageBucket: 'calendar-management-233888.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-CWwC9FMFHIOqrrLoBrKvQsGMmTQWLMM',
    appId: '1:82853880537:ios:3ec34d178bba7a3c75d4c8',
    messagingSenderId: '82853880537',
    projectId: 'calendar-management-233888',
    storageBucket: 'calendar-management-233888.appspot.com',
    iosClientId: '82853880537-40st1487k8v34jcohv60cqflldcmhck5.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-CWwC9FMFHIOqrrLoBrKvQsGMmTQWLMM',
    appId: '1:82853880537:ios:3ec34d178bba7a3c75d4c8',
    messagingSenderId: '82853880537',
    projectId: 'calendar-management-233888',
    storageBucket: 'calendar-management-233888.appspot.com',
    iosClientId: '82853880537-40st1487k8v34jcohv60cqflldcmhck5.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendarApp',
  );
}
